### ISSUE TITLE
vfs-zip, async I/O, and future plans

### ISSUE THREAD

**Issue by MaulingMonkey** [manuel-woelker/rust-vfs#10]
Hello!  I've created [vfs-zip](https://github.com/MaulingMonkey/vfs-zip), allowing vfs to read from .zip files, and thought I'd share a few questions and meandering thoughts.

* Would you be interested in async APIs?  Browsers lack blocking I/O, so the current abstractions don't really work if you wanted to write a browser-compatible `HttpFS` - instead you'd need to use something entirely loaded up-front like MemoryFS or <code>vfs_zip::[ZipReadOnly](https://docs.rs/vfs-zip/0.1.0/vfs_zip/struct.ZipReadOnly.html)&lt;std::io::Cursor&lt;Vec&lt;u8&gt;&gt;&gt;</code>.

* It'd be nice to get rid of the boxes in **trait FileSystem** by extending it to have something like:
  ```rust
  type ReadDirEntry : AsRef<str> + Into<String> + Display;
  type ReadDir : Iterator<Item = Self::ReadDirEntry>;
  fn read_dir(&self, path: &str) -> VfsResult<Self::ReadDir>;
  ```
  This would eliminate some virtual dispatch overhead if you wanted to have `FileSystem`s wrapping other `FileSystem`s, or if you wanted to directly use `&impl FileSystem`s.  `Box<dyn FileSystem>` and/or `Rc<dyn FileSystem>` could implement `FileSystem` with the existing boxes.

* It'd be nice to relax the `Send`+`Sync` requirements of FileSystem.  `vfs-zip` (and likely other archive readers) are currently forced to resort to mutexes... I suppose that's a natural consequence of `VfsPath` internally storing an `Arc<Box<dyn FileSystem>>` though.

I'm also vaguely interested in writing more VFS abstractions for:
* Generic servers (`GET` / `PUT` over HTTP(S)? SSH so I can talk to a mac mini or linux vm from my windows machine?)
* VCS servers (it'd be nice to be able to treat, say, a git commit or perforce revision as a filesystem to read from the server on-demand)
* On-demand filesystems (e.g. requesting `some/game/shader.bin` might compile `some/game/shader.hlsl` on the fly)
* Multi-disk caching filesystems  - e.g. writing `foo/bar` might copy/move files from `C:\SddCache` → `D:\SlowDiskCache` → `E:\BiggerSlowerDiskCache` → `//SomeNAS/Cache` - possibly deleting/evicting files that haven't been used in awhile based on configuration files / size limits / file extensions.

I'm unlikely to write this all at once, or anytime soon, but thought I'd share what I'm considering tackling, check what (if anything) can/should be upstreamed into vfs itself, and make sure nobody's about to beat me to the punch.

**Comment by manuel-woelker** [comment]
Thanks for your write-up! Here are my thoughts:

1. async io: I haven't had much need for an async vfs API. Since the API would probably look quite a bit different, it might make sense to handle this in a separate crate.
2. The previous version used an unboxed trait system. While this avoided virtual dispatch overhead, it made the API quite unwieldy.
I am not totally sure but I suspect `VfsResult<Self::ReadDir>` might not work due `Self::ReadDir` being unsized. I remember running into issues like this in the previous iteration, which is why I decided to accept the dispatch overhead in exchange for a simpler API.
For most cases the IO itself should be the bottleneck rather than the dispatch, and if that's really a performance critical issue using a VFS might not be a great idea in the first place.
3. I wanted the API to be as flexible as possible to use, even at the cost of FS implementation work. In general filesystems allow concurrent access, which is why I wanted to support this in the API. Regarding a zip VFS, for a purely read-only implementation a `Sync+Send` implementation should be rather straight-forward by wrapping a `VfsPath`.
As mentioned in #11 I had only considered read-only zip VFS, since I susprect transparent zip write access might be quite hairy.

4. Regarding future FS implementations: Great ideas! Looking forward to see those, I especially like the on-demand "asset materialization". This should probably allow recompilation on the fly during development, while shipping precompiled shaders for production using the same file paths and infrastructure.
AFAICT the `FileSystem` trait should allow these use cases. Let me know if you run into any issues.
At the moment I don't see a pressing need to upstream any implementations into rust-vfs itself since they can be consumed just as easily as specialized crates.

**Comment by manuel-woelker** [comment]
I just took a look at `ZipReadOnly` and had the following ideas to address the Sync and copy issues: 

1. As mentioned above, rather than storing an archive in a mutex, it might be possible to store a VfsPath an open the archive as necessary. This would allow concurrent reads, at the cost of reopening the file.
2. Alternatively, use a function that produces the `IO` on demand. This would also allow multiple archives/reads.
3. Probably much more complicated for little benefit: Create something like a `SharedCursor` implementing `Read+Seek` with an `Arc<Mutex<IO>>` wrapping the IO. This would also allow each access to open their own private view/archive into the shared IO. A lot more effort, but would preserve the current API.

**Comment by MaulingMonkey** [comment]
Thanks for taking the time to respond, fair points all around 👍 

* RE 1:  A separate crate for async I/O works for me.  It should be easy enough to write adapters to allow reusing the convenient blocking I/O provided by vfs on the majority of platforms where they're available.

* RE 2:  I've begun experimenting a little with this on my own, and see your point about it getting unwieldy.  IO certainly should dominate for most use cases... and while I do have in mind some use cases involving high frequency access of tiny files, vfs might be the wrong stage to try and tackle those at.  I can always write `unwieldy-vfs` with adapters ;)

* RE 3:  Also fair.

* RE 4:  On-demand asset materialization is super useful.  Professional gamedev codebases often have hundreds of gigabytes of assets - perhaps terrabytes these days - and building all that up front just to test a little development level is impossibly painful, especially when the artists start reorganizing directories 🤣.  Massive overkill for my hobby needs, but I still miss it.  And, yes, the existing FileSystem trait should probably work fine for all these use cases.

---

RE ZipOnly 1/2/3:  There are definitely ways to parallelize it.  Something similar to a SharedCursor is actually not the worst idea - some platforms implement read functions that let you specify a seek offset when reading, so you can use a single file handle to read from multiple locations simultaniously without fighting over shared file-handle-wide seek state.  An `Arc<Vec<Mutex<IO>>` mimics that as a decent fallback for the platforms that don't have similar.

I probably won't write it anytime soon - my performance needs aren't that great yet - but it's in the back of my mind at least.

**Comment by manuel-woelker** [comment]
Thanks for the valuable feedback, please let me know if you run into any issues.

**Comment by prabirshrestha** [comment]
I have implemented an [async-vfs](https://github.com/prabirshrestha/async-vfs) which is based on async-std. It is also available in [crates.io](https://crates.io/crates/async-vfs). async was important for me as I need to support cloud storage in the future but for now it only supports the physical os file system.

Next goal is to implement a webdav server on top of the async-vfs.
